### ISSUE TITLE
Implement a logic to not do anything if the same request was already sent previously

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-restapi-backend#9]
This should have multiple checks:
1) Check to see what values are sent to be verified
2) Check whether the same request with the same values were already sent within the last 10 minutes
3) Return an appropriate response saying a similar request was already submitted in the last 10 minutes

**Comment by wakqasahmed** [comment]
/create endpoint is returning the following:

{"meta": {"code": 500, "message": "Unknown Error", "description": "A similar request was already submitted in the last 10 minutes"}}

Please update the message to be either a warning or a failure e.g.
"Same request can't be submitted" OR 
"Request already in process" (Recommended) OR
"Duplicate request failed"
